set(MOSAIC_APP_NAME liquid)
set(MOSAIC_APP_MODULE_SOURCE liquid_app.c)
set(MOSAIC_APP_MODULE_SYMBOL mosaic_liquid_app)
set(MOSAIC_APP_BUNDLE generated/liquid.gspb)
set(MOSAIC_APP_SCENE_DIR scene)
set(MOSAIC_APP_SCENE_JSON scene/liquid_480.json)
set(MOSAIC_APP_GENERATOR scene/gen_scene.py)
set(MOSAIC_APP_EXTRA_SOURCES liquid_engine.c liquidduck/flip.cpp)
set(MOSAIC_APP_TICK_MS 33)
