#!/usr/bin/env python3
"""Generate project-private glyphs needed by the LVGL HSV/connection labels."""
import hashlib
from pathlib import Path
import sys
from PIL import Image, ImageDraw, ImageFont
source = Path(sys.argv[1])
expected = 'a3041811a78c361b1de50f953c805e0244951c21c5bd412f7232ef0d899af0da'
if hashlib.sha256(source.read_bytes()).hexdigest() != expected:
    raise SystemExit('Use the Noto Sans SC source pinned by shared ux-components/fonts/source.sha256')
font = ImageFont.truetype(str(source), 24)
font.set_variation_by_name('Regular')
data, glyphs = [], []
characters=sorted(set('相饱和窗口协议支加密'), key=ord)
for ch in characters:
    x0,y0,x1,y1 = font.getbbox(ch, anchor='ls')
    width,height=x1-x0,y1-y0
    image=Image.new('L',(width,height),0)
    ImageDraw.Draw(image).text((-x0,-y0),ch,font=font,fill=255,anchor='ls')
    values=[round(p/17) for p in image.get_flattened_data()]
    if len(values)%2: values.append(0)
    glyphs.append((ord(ch),len(data),x0,y0+25,width,height,round(font.getlength(ch))))
    data.extend((values[i]<<4)|values[i+1] for i in range(0,len(values),2))
lines=['// Generated by tools/generate_lvgl_font.py; Noto Sans SC, OFL-1.1.',
       '#include <UxText.h>', 'namespace {', 'const uint8_t pixels[] = {']
lines.extend('    '+','.join(map(str,data[i:i+32]))+',' for i in range(0,len(data),32))
lines+=['};','const ux::Glyph glyphs[] = {']
lines+=['    {'+','.join(map(str,g))+'},' for g in glyphs]
lines+=['};','}',f'extern const ux::Font WatchExtra24={{glyphs,pixels,{len(characters)},29}};']
(Path(__file__).resolve().parents[1]/'src/WatchLvglFont.cpp').write_text('\n'.join(lines)+'\n')
