#!/usr/bin/env python3
"""Generate the fixed-scanline RGB565 settings icon asset header."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from PIL import Image


WIDTH = 200
HEIGHT = 200
NAMES = ("time", "bot", "display", "sound", "power")


def rgb565_pixels(path: Path) -> np.ndarray:
    image = Image.open(path).convert("RGB")
    if image.size != (WIDTH, HEIGHT):
        raise ValueError(f"{path}: expected {WIDTH}x{HEIGHT}, got {image.size}")
    rgb = np.asarray(image, dtype=np.uint16)
    return (((rgb[:, :, 0] >> 3) << 11)
            | ((rgb[:, :, 1] >> 2) << 5)
            | (rgb[:, :, 2] >> 3)).astype(np.uint16)


def fnv1a565(pixels: np.ndarray) -> int:
    value = 0x811C9DC5
    for pixel in pixels.flat:
        raw = int(pixel)
        value = ((value ^ (raw & 0xFF)) * 0x01000193) & 0xFFFFFFFF
        value = ((value ^ (raw >> 8)) * 0x01000193) & 0xFFFFFFFF
    return value


def encode_packbits(pixels: np.ndarray) -> bytes:
    """Lossless row-local PackBits for native-order RGB565 words.

    A command byte stores a one-to-128 pixel length minus one. Bit seven means
    one RGB565 word is repeated; a clear bit means that many literal words.
    Commands never cross a row, which bounds the decoder to one 400-byte line.
    """
    output = bytearray()
    for row in pixels:
        x = 0
        while x < WIDTH:
            run_end = x + 1
            while (run_end < WIDTH and run_end - x < 128
                   and row[run_end] == row[x]):
                run_end += 1
            if run_end - x >= 3:
                output.append(0x80 | (run_end - x - 1))
                output.extend(int(row[x]).to_bytes(2, "little"))
                x = run_end
                continue

            literal_start = x
            x = run_end
            while x < WIDTH and x - literal_start < 128:
                run_end = x + 1
                while (run_end < WIDTH and run_end - x < 128
                       and row[run_end] == row[x]):
                    run_end += 1
                if run_end - x >= 3:
                    break
                remaining = 128 - (x - literal_start)
                x += min(run_end - x, remaining)
            literal_length = x - literal_start
            output.append(literal_length - 1)
            for pixel in row[literal_start:x]:
                output.extend(int(pixel).to_bytes(2, "little"))
    return bytes(output)


def decode_packbits(data: bytes, row_count: int) -> np.ndarray:
    """Reference decoder used to prove the generator's command boundaries."""
    result = np.zeros((row_count, WIDTH), dtype=np.uint16)
    offset = 0
    for y in range(row_count):
        x = 0
        while x < WIDTH:
            control = data[offset]
            offset += 1
            count = (control & 0x7F) + 1
            if count > WIDTH - x:
                raise ValueError("PackBits command crosses a scanline")
            if control & 0x80:
                pixel = int.from_bytes(data[offset:offset + 2], "little")
                offset += 2
                result[y, x:x + count] = pixel
            else:
                for _ in range(count):
                    result[y, x] = int.from_bytes(data[offset:offset + 2], "little")
                    offset += 2
                    x += 1
                continue
            x += count
    if offset != len(data):
        raise ValueError("trailing PackBits data")
    return result


def verify_codec_boundaries() -> None:
    # This shape previously let a two-pixel run extend a 127-pixel literal to
    # 129, setting the command's repeat bit. It must split at exactly 128.
    boundary = np.arange(WIDTH, dtype=np.uint16).reshape(1, WIDTH)
    boundary[0, 127:129] = 0x6B4A
    packed = encode_packbits(boundary)
    if not np.array_equal(decode_packbits(packed, 1), boundary):
        raise AssertionError("PackBits 127-literal/two-equal boundary failed")


def bytes_literal(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        values = ", ".join(f"0x{value:02X}" for value in data[offset:offset + 16])
        rows.append(f"    {values},")
    return "\n".join(rows)


def generate(source_dir: Path, output: Path) -> None:
    verify_codec_boundaries()
    encoded = []
    for name in NAMES:
        pixels = rgb565_pixels(source_dir / f"{name}.png")
        encoded.append((name, encode_packbits(pixels), fnv1a565(pixels)))

    parts = ["""// Generated by tools/generate_settings_icon_assets.py. Do not edit.
#pragma once

#include <stddef.h>
#include <stdint.h>

#if defined(ARDUINO_ARCH_ESP32)
#include <pgmspace.h>
#define WATCH_SETTINGS_ICON_FLASH PROGMEM
#else
#define WATCH_SETTINGS_ICON_FLASH
#endif

namespace lgfx { inline namespace v1 { struct rgb565_t; } }

namespace watchsettingsiconassets {

constexpr int16_t Width = 200;
constexpr int16_t Height = 200;
constexpr size_t ScanlineBytes = Width * sizeof(uint16_t);

enum class Icon : uint8_t { Time, Bot, Display, Sound, Power, Count };

struct Asset {
    const uint8_t* data;
    size_t size;
    uint32_t pixelHash;
};
"""]
    for name, data, _ in encoded:
        symbol = f"k{name.title()}Data"
        parts.append(f"\nstatic const uint8_t {symbol}[] WATCH_SETTINGS_ICON_FLASH = {{\n")
        parts.append(bytes_literal(data))
        parts.append("\n};\n")

    parts.append("\nstatic const Asset kAssets[] = {\n")
    for name, _, pixel_hash in encoded:
        symbol = f"k{name.title()}Data"
        parts.append(f"    {{{symbol}, sizeof({symbol}), 0x{pixel_hash:08X}u}},\n")
    parts.append("""};

inline const Asset* asset(Icon icon) {
    uint8_t index = (uint8_t)icon;
    return index < (uint8_t)Icon::Count ? &kAssets[index] : nullptr;
}

inline uint8_t readByte(const uint8_t* address) {
#if defined(ARDUINO_ARCH_ESP32)
    return pgm_read_byte(address);
#else
    return *address;
#endif
}

class Reader {
public:
    explicit Reader(const Asset& asset): _asset(asset) {}

    template<class Pixel>
    bool readRow(Pixel output[Width]) {
        if (_row >= Height) return false;
        int16_t x = 0;
        while (x < Width) {
            if (_offset >= _asset.size) return false;
            uint8_t control = readByte(_asset.data + _offset++);
            uint16_t count = (uint16_t)(control & 0x7F) + 1;
            if (count > (uint16_t)(Width - x)) return false;
            if (control & 0x80) {
                uint16_t pixel;
                if (!readPixel(pixel)) return false;
                for (uint16_t i = 0; i < count; ++i) output[x++] = pixel;
            } else {
                for (uint16_t i = 0; i < count; ++i) {
                    uint16_t pixel;
                    if (!readPixel(pixel)) return false;
                    output[x++] = pixel;
                }
            }
        }
        ++_row;
        return true;
    }

    bool complete() const { return _row == Height && _offset == _asset.size; }
    size_t bytesRead() const { return _offset; }
    int16_t rowsRead() const { return _row; }

private:
    bool readPixel(uint16_t& pixel) {
        if (_asset.size - _offset < 2) return false;
        uint8_t low = readByte(_asset.data + _offset++);
        uint8_t high = readByte(_asset.data + _offset++);
        pixel = (uint16_t)(low | ((uint16_t)high << 8));
        return true;
    }

    const Asset& _asset;
    size_t _offset = 0;
    int16_t _row = 0;
};

template<class Canvas>
struct NativePixel { typedef lgfx::rgb565_t Type; };

// Decode one native-order RGB565 row at a time, then submit it through M5GFX's
// typed pixel overload. The only working storage is this 400-byte scanline.
template<class Canvas>
bool draw(Canvas& canvas, Icon icon, int16_t centerX, int16_t centerY) {
    const Asset* selected = asset(icon);
    if (!selected) return false;
    Reader reader(*selected);
    typename NativePixel<Canvas>::Type scanline[Width];
    const int32_t left = centerX - Width / 2;
    const int32_t top = centerY - Height / 2;
    const int32_t canvasWidth = canvas.width();
    const int32_t canvasHeight = canvas.height();
    const int16_t sourceX = left < 0 ? (int16_t)-left : 0;
    const int32_t targetX = left < 0 ? 0 : left;
    int32_t visibleWidth = Width - sourceX;
    if (targetX + visibleWidth > canvasWidth)
        visibleWidth = canvasWidth - targetX;

    for (int16_t row = 0; row < Height; ++row) {
        if (!reader.readRow(scanline)) return false;
        int32_t targetY = top + row;
        if (targetY < 0 || targetY >= canvasHeight || visibleWidth <= 0
            || targetX >= canvasWidth)
            continue;
        canvas.pushImage(targetX, targetY, visibleWidth, 1, scanline + sourceX);
    }
    return reader.complete();
}

} // namespace watchsettingsiconassets

#undef WATCH_SETTINGS_ICON_FLASH
""")
    output.write_text("".join(parts), encoding="utf-8")
    raw_size = WIDTH * HEIGHT * 2 * len(encoded)
    packed_size = sum(len(data) for _, data, _ in encoded)
    print(f"wrote {output}")
    print(f"RGB565 PackBits: {packed_size:,} / {raw_size:,} bytes "
          f"({packed_size / raw_size:.1%})")
    for name, data, pixel_hash in encoded:
        print(f"{name:7s} {len(data):6,d} bytes  FNV1a565=0x{pixel_hash:08X}")


def main() -> None:
    project = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path,
                        default=project / "assets" / "settings-icons")
    parser.add_argument("--output", type=Path,
                        default=project / "include" / "WatchSettingsIconAssets.h")
    args = parser.parse_args()
    generate(args.source, args.output)


if __name__ == "__main__":
    main()
